name:                haskell-json-parser
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  parse-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parse-json
